name: pavel_dvorak
description: Osobní webové stránky Pavla Dvořáka – chemika, tanečníka, seveřana
version: 1.8.0
homepage: https://www.dvorapa.cz

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  dialog: '>=0.8.0 <1.0.0'
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.1.5
  build_web_compilers: ^3.2.1
  grinder: '>=0.9.0 <1.0.0'
  lints: ^1.0.1
