name: pavel_dvorak
description: Osobní webové stránky Pavla Dvořáka – chemika, tanečníka, seveřana
version: 1.7.2
author: Pavel Dvořák
homepage: https://www.dvorapa.cz

environment:
  sdk: ">=2.9.3 <3.0.0"

dependencies:
  dialog: ">=0.7.2 <1.0.0"
  yaml: ^2.2.1

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  grinder: ">=0.8.6 <1.0.0"
